# Generated by Django 5.0.4 on 2024-05-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post_images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADM', 'Administrator'), ('AUT', 'Author'), ('SUB', 'Subscriber')], default='SUB', max_length=3),
        ),
    ]
