# Generated by Django 5.0.4 on 2024-05-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_partial_content_to_show_alter_post_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='partial_content_to_show',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
